/** @type {import('tailwindcss').Config} */
// AILearn Soft-Modernist design tokens (from templates/ailearn_soft_utility/DESIGN.md)
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx,js,jsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#e8e2d6',
        'on-primary-fixed': '#201b12',
        'secondary-fixed': '#e9e2d4',
        'surface-container': '#f2ede3',
        'surface-variant': '#e7e2d8',
        'inverse-surface': '#32302a',
        'on-primary-container': '#fffbff',
        background: '#fef9ef',
        surface: '#fef9ef',
        'on-background': '#1d1c16',
        outline: '#7d766d',
        error: '#ba1a1a',
        'on-surface-variant': '#4b463e',
        'surface-container-high': '#ede8de',
        'tertiary-container': '#78746a',
        primary: '#635b4f',
        'on-error': '#ffffff',
        'surface-bright': '#fef9ef',
        'inverse-on-surface': '#f5f0e6',
        'on-tertiary-fixed': '#1e1c14',
        'on-secondary': '#ffffff',
        secondary: '#625e54',
        'surface-dim': '#dedad0',
        'inverse-primary': '#d0c5b6',
        'error-container': '#ffdad6',
        'on-tertiary-container': '#fffbff',
        'on-secondary-fixed-variant': '#4a463d',
        'surface-container-highest': '#e7e2d8',
        'primary-fixed': '#ece1d2',
        'on-surface': '#1d1c16',
        'on-primary': '#ffffff',
        'on-secondary-container': '#696459',
        'outline-variant': '#cec5bb',
        'on-error-container': '#93000a',
        'surface-tint': '#655d51',
        'surface-container-low': '#f8f3e9',
        tertiary: '#5f5c52',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed': '#1e1b13',
        'tertiary-fixed-dim': '#cbc6ba',
        'primary-container': '#7c7367',
        'primary-fixed-dim': '#d0c5b6',
        'secondary-fixed-dim': '#ccc6b9',
        'on-tertiary-fixed-variant': '#4a473e',
        'secondary-container': '#e9e2d4',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#4d463b',
        // Dark-mode warm charcoal (from DESIGN.md)
        'dark-surface': '#1A1917',
        'dark-surface-elevated': '#22201D',
        'dark-on-surface': '#EDE8DE',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        '4xl': '3rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        unit: '4px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        'container-max': '1280px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        headline: ['Literata', 'serif'],
        body: ['Manrope', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
      },
      boxShadow: {
        ambient: '0 4px 24px rgba(29, 28, 22, 0.06)',
        'ambient-lg': '0 12px 48px rgba(29, 28, 22, 0.08)',
        'dark-ambient': '0 4px 24px rgba(0, 0, 0, 0.4)',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(6px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.3s ease-out',
      },
    },
  },
  plugins: [],
}
