/** @type {import('tailwindcss').Config} */
// AIScope "Parchment" palette — aged-paper warm tones for light mode and
// dark leather-brown for dark mode. A few cool accents (olive, slate) are
// kept for data colors so charts still read clearly.
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx,js,jsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#EFE6D2',
        'on-primary-fixed': '#2E1F0E',
        'secondary-fixed': '#EFE6D2',
        'surface-container': '#EDE2CB',
        'surface-variant': '#E9DEC6',
        'inverse-surface': '#3B3023',
        'on-primary-container': '#FFF8EC',
        background: '#F7F0E3',
        surface: '#F7F0E3',
        'on-background': '#3B3023',
        outline: '#8A7A61',
        error: '#A94535',
        'on-surface-variant': '#6B5D48',
        'surface-container-high': '#E6D9BE',
        'tertiary-container': '#D8CBB0',
        primary: '#7A5C36',
        'on-error': '#FFFFFF',
        'surface-bright': '#FCF8EF',
        'inverse-on-surface': '#F7F0E3',
        'on-tertiary-fixed': '#211B10',
        'on-secondary': '#FFFFFF',
        secondary: '#6E5F49',
        'surface-dim': '#DFD2B6',
        'inverse-primary': '#E7CC9F',
        'error-container': '#F5D9CE',
        'on-tertiary-container': '#211B10',
        'on-secondary-fixed-variant': '#4A3E2E',
        'surface-container-highest': '#DFCFB0',
        'primary-fixed': '#EBD9BC',
        'on-surface': '#3B3023',
        'on-primary': '#FFF8EC',
        'on-secondary-container': '#54483A',
        'outline-variant': '#CBBBA0',
        'on-error-container': '#5C1D12',
        'surface-tint': '#7A5C36',
        'surface-container-low': '#F3EBD9',
        tertiary: '#5E6151',
        'on-tertiary': '#FFFFFF',
        'on-secondary-fixed': '#221B10',
        'tertiary-fixed-dim': '#C5BA9F',
        'primary-container': '#E4C9A0',
        'primary-fixed-dim': '#D4B882',
        'secondary-fixed-dim': '#D3C5A8',
        'on-tertiary-fixed-variant': '#444838',
        'secondary-container': '#EFE6D2',
        'surface-container-lowest': '#FCF8EF',
        'on-primary-fixed-variant': '#5C4423',
        // Dark mode — aged leather / old-book browns
        'dark-surface': '#1E1913',
        'dark-surface-elevated': '#2A2319',
        'dark-on-surface': '#ECE2CD',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        '4xl': '3rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        unit: '4px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        'container-max': '1280px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        // Latin/numbers first (mono), then CJK clerical script (隶书).
        // Per-glyph fallback: Latin uses mono, CJK falls through to lisu/STLiti.
        headline: ['"JetBrains Mono"', '"Cascadia Code"', '"Fira Code"', 'Consolas',
          '"STLiti"', '"华文隶书"', '"LiSu"', '"隶书"', '"STXingkai"', '"华文行楷"',
          '"Ma Shan Zheng"', '"ZCOOL XiaoWei"',
          '"PingFang SC"', '"Hiragino Sans GB"', '"Microsoft YaHei"', 'serif'],
        body: ['"JetBrains Mono"', '"Cascadia Code"', '"Fira Code"', 'Consolas',
          '"STLiti"', '"华文隶书"', '"LiSu"', '"隶书"', '"STXingkai"', '"华文行楷"',
          '"Ma Shan Zheng"', '"ZCOOL XiaoWei"',
          '"PingFang SC"', '"Hiragino Sans GB"', '"Microsoft YaHei"', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"Cascadia Code"', '"Fira Code"', 'Consolas',
          'ui-monospace', 'monospace'],
        codex: ['"JetBrains Mono"', '"Cascadia Code"', '"Fira Code"', 'Consolas',
          '"STLiti"', '"华文隶书"', '"LiSu"', '"隶书"',
          '"Ma Shan Zheng"', '"ZCOOL XiaoWei"',
          '"PingFang SC"', '"Hiragino Sans GB"', '"Microsoft YaHei"', 'serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
      },
      boxShadow: {
        ambient: '0 4px 24px rgba(59, 48, 35, 0.08)',
        'ambient-lg': '0 12px 48px rgba(59, 48, 35, 0.12)',
        'dark-ambient': '0 4px 24px rgba(0, 0, 0, 0.45)',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(6px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.3s ease-out',
      },
    },
  },
  plugins: [],
}
